### ISSUE TITLE
好像有跨域问题，是我哪里配置不正确？

### ISSUE THREAD

**Issue by shaokeke** [MQEnergy/mqshop-admin#3]
![image](https://github.com/MQEnergy/mqshop-admin/assets/37448773/e9b1bc24-f3e2-4329-89e7-59974d5a533c)

**Comment by chenxi2015** [comment]
这个需要配合 https://github.com/MQEnergy/mqshop 接口使用的，具体使用可查看mqshop的readme文档，目前还在开发中...

**Comment by shaokeke** [comment]
可以了，是vite的版本问题造成的跨域问题，我从5.3.1 换成5.2.0就可以了
